### ISSUE TITLE
Does not track removals

### ISSUE THREAD

**Issue by FichteFoll** [TheSecEng/Sublime-Text-API-Tracker#31]
4078 removed `subime.Settings.__iter__`.

**Comment by TheSecEng** [comment]
Thoughts?

https://raw.githubusercontent.com/TheSecEng/Sublime-Text-API-Tracker/v2/exploration/sublime_api_list.json

**Comment by FichteFoll** [comment]
I mentioned this on Discord briefly, but the change made it *significantly* harder to spot at a glance which API was added in which build. It also blew up the JSON to almost 20k lines. I don't think copying and maintaining an "unchanged" list is worthwhile or even useful, outside of automatic checking of some sort, which doesn't exist at the moment and could still very easily be constructred from the added or removed lists.

**Comment by TheSecEng** [comment]
@FichteFoll I agree with you, 20K lines of JSON threw me off as well. I will push a change tonight to have 2 list `sublime_api_list.json` and `sublime_api_diffs.json` which should allow for a list with all of the current API's and then a list of when an API was added and when one was removed.

**Comment by TheSecEng** [comment]
Fixed with latest version

**Comment by FichteFoll** [comment]
Thanks, looking good now.
